In [1]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
print('Libraries imported')

Libraries imported

In [2]:
df = pd.read_csv("./gene_expression (1).csv")
print('columns:', df.columns.tolist())
print(df.head(3))

       Gene One  Gene Two  Cancer Present
0           4.3       3.9               1
1           2.5       6.3               0
2           5.7       3.9               1
3           6.1       6.2               0
4           7.4       3.4               1

In [5]:
df

          Gene One  Gene Two  Cancer Present
0              4.3       3.9               1
1              2.5       6.3               0
2              5.7       3.9               1
3              6.1       6.2               0
4              7.4       3.4               1
...            ...       ...             ...
2995           5.0       6.5               1
2996           3.4       6.6               0
2997           2.7       6.5               0
2998           3.3       5.6               0
2999           4.6       8.2               0

[3000 rows x 3 columns]

In [6]:
sns.scatterplot(data=df,x="Gene One",y="Gene Two",hue="Cancer Present",style="Cancer Present",alpha=0.6)
plt.xlim(1,8)

ValueError: Could not interpret value `Gene One` for `x`. An entry with this name does not appear in `data`.

In [ ]:
sns.pairplot(data=df,hue='Cancer Present')

In [ ]:
X = df.drop('Cancer Present',axis=1)

In [ ]:
y=df['Cancer Present']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,train_size=101)

In [ ]:
scaler  = StandardScaler()
scaled_X_train = scaler.fit_transform(X_train)
scaled_X_test = scaler.transform(X_test)

In [ ]:
scaled_X_test

In [ ]:
scaled_X_test

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
KNN_neighbor = KNeighborsClassifier()

# 2. Fit the model on the scaled training data
KNN_neighbor.fit(scaled_X_train, y_train)

# 3. Predict the labels for the test dataset
y_predict_KN = KNN_neighbor.predict(scaled_X_test)

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
confusion_matrix(y_test,y_predict_KN)

In [ ]:
KNN_neighbor = KNeighborsClassifier()

# 2. Fit the model on the scaled training data
KNN_neighbor.fit(scaled_X_train, y_train)

# 3. Predict the labels for the test dataset
y_predict_KN = KNN_neighbor.predict(scaled_X_test)
scaler  = StandardScaler()
scaled_X_train = scaler.fit_transform(X_train)
scaled_X_test = scaler.transform(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
test_error= []
for k in range(1,30):
    
    KNN_model = KNeighborsClassifier(n_neighbors=k)
    KNN_model.fit(scaled_X_test,y_train)
    KNN_predict = KNN_model.predict(scaled_X_test)
    KNN_accu=1-accuracy_score(test_error)
    test_error.append(KNN_accu)
    print(test_error)

PIPLINE ----> GridsearchCV

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
KNN = KNeighborsClassifier()

In [ ]:
scaler = StandardScalar()

In [ ]:
from sklearn.pipline import Pipiline

In [ ]:
operations = {('scaler',scaler),('KNN',KKN)}

In [ ]:
pipe = Pipeline(operations)

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
k_values=List(range(1,20))

In [ ]:
params = {'KNN__n_neighbors':k_values}

In [ ]:
full_cv_classifier = GridSearchCV(pipe,params,cv=5,scoring='accuracy')

In [ ]:
full_cv_classifier.fit(X_train,y_train)

In [ ]:
full_cv_classifier.best_estimator_.get_params()

In [ ]:
full_pred=full_cv_classifier.predict(X_test)

In [ ]:
print(classification_report(y_test,full_pred))

In [ ]:
new_patient = [[3.8,6.4]]

In [ ]:
full_cv_classifier.predict(new_patient)

In [ ]:
full_cv_classifier.predict_prob(new_patient)

In [ ]:
full_pred = full_cv_classifier.predict(X_test)

In [ ]:
print(classification_report(y_train,full_pred
                            ))